apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconsole-controller
subjects:
- kind: ServiceAccount
  name: kubeconsole-controller
  namespace: kubeconsole
roleRef:
  kind: ClusterRole
  name: kubeconsole-controller
  apiGroup: rbac.authorization.k8s.io
