apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeconsole-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeconsole-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeconsole-controller
    spec:
      serviceAccountName: kubeconsole-controller
      containers:
        - image: lisinge/kubeconsole-controller:v0.0.2
          name: kubeconsole-controller
          resources:
            requests:
              memory: "100Mi"
              cpu: "20m"
          env:
            - name: VERBOSE
              value: "true"
