apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeconsole

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml

images:
  - name: micke/kubeconsole-controller
    newTag: v1.0.0
